#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';
require_once 'src/Bootstrap/Autoloader.php';

$autoloader = new \Application\Bootstrap\Autoloader();
$autoloader->setConfigPath('config/');
$autoloader->addIncludePath('src/');
$autoloader->setApplicationPath('application/');
$autoloader->run();

$application = new \Application\Application();
$application->setAutoloader($autoloader);
$application->console();